### ISSUE TITLE
Release the code

### ISSUE THREAD

**Issue by bmorphism** [epfl-dlab/aiflows#1]
The flow must begin!

**Comment by nick-talati** [comment]
Open the gates!

**Comment by martinj96** [comment]
The enthusiasm is much appreciated! 

Apologies for the delay. We wanted to release the library well documented, with tutorials etc, so that you can get started as smoothly as possible. 

The floodgates are now open and won't be closing. The flow just began! 

Would love to hear your feedback. We'll soon share two write-ups about the long-term vision for the project, outlining both research and implementation challenges. Would love to hear that you "early believers" would like to stay involved. If that's the case I'd be happy to meet and discuss promising directions from your perspective and how we can support them.

Cheers!
