### ISSUE TITLE
Doesn't work on Python 3.11

### ISSUE THREAD

**Issue by jiahao42** [epfl-dlab/aiflows#2]
### Documentation

Hello, thanks for releasing the source code. I had a quick try and I found the repo doesn't build on Python 3.11, the build error is from [pyFirmata](https://github.com/tino/pyFirmata), see https://stackoverflow.com/a/74586109.

I tried on Python 3.10 and had no issues. Maybe it's worth mentioning it in https://github.com/epfl-dlab/aiflows/blob/main/README.md#installation. Thanks!

**Comment by martinj96** [comment]
Hi Jiahao, 

Thanks for noticing the problem and identifying its source! We'll look into and find a solution that works for both Python 3.10 and 3.11, so I will keep the issue open until this is taken care of.

**Comment by nbaldwin98** [comment]
Hi @jiahao42 ,
I've fixed this and aiflows should work on python 3.11.
It's worth noting that installing aiflows on Python 3.12 is not recommended. Some flows from the FlowVerse, such as the [VectorStoreFlowModule](https://huggingface.co/aiflows/VectorStoreFlowModule) used in AutoGPTFlow, may have dependencies that are incompatible with Python 3.12. For instance, the dependency to chromadb within VectorStoreFlowModule appears to be unattainable in Python 3.12 due to its pulsar-client dependency.

**Comment by jiahao42** [comment]
Thank you so much for fixing it so quickly, appreciate it!
